version: 2.1 # Use version 2.1 to enable Orb usage.

orbs:
  win: circleci/windows@2.2.0 # The Windows orb give you everything you need to start using the Windows executor.
jobs:
  build: # name of your job
    executor: win/default # executor type
    steps:
      - checkout
      - run: Write-Host 'Installing GCloud SDK'
      - run: choco install gcloudsdk --ignore-checksums
      - run: |
          echo $env:GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project $env:GOOGLE_PROJECT_ID
          gcloud --quiet config set compute/zone $env:GOOGLE_COMPUTE_ZONE
      - run: gcloud auth configure-docker
      - run:
          command: |
            GIT_TAG=`git describe --tags $(git rev-list --tags --max-count=1 2>/dev/null)`
            docker build -t "gcr.io/releaseinf/windowstest:$GIT_TAG" .
            docker push "gcr.io/releaseinf/windowstest:$GIT_TAG"
          shell: bash.exe
