version: 2.1
orbs:
  win: circleci/windows@2.2.0
jobs:
  build: windows-test-commit
    executor: win/default

    steps:
    # Commands are run in a Windows virtual machine environment
      - checkout
      - run: Write-Host 'Hello, Windows'
