version: 2.1 # Use version 2.1 to enable Orb usage.

orbs:
  win: circleci/windows@2.2.0 # The Windows orb give you everything you need to start using the Windows executor.
jobs:
  build: # name of your job
    executor: win/default # executor type
    steps:
      - checkout
      - run: Write-Host 'Installing GCloud SDK'
      - run: (New-Object Net.WebClient).DownloadFile("https://dl.google.com/dl/cloudsdk/channels/rapid/GoogleCloudSDKInstaller.exe", "$env:Temp\GoogleCloudSDKInstaller.exe")
      - run: $env:Temp\GoogleCloudSDKInstaller.exe /S 
